import { RecruitingEvent } from "./types";
export const mockEvents: RecruitingEvent[] = [
  {
    id: "perplexity-tech-talk",
    slug: "perplexity-ai-campus-tech-talk",
    title: "Building Search That Thinks: Campus Tech Talk",
    description:
      "Join Perplexity engineers for a candid discussion on retrieval systems, evaluation, and building reliable AI products. A recruiter Q&A and informal networking follow the talk.",
    company: "Perplexity",
    companyInitials: "P",
    companyColor: "#163c3c",
    startAt: "2026-09-23T18:00:00-04:00",
    endAt: "2026-09-23T19:30:00-04:00",
    location: "Gates Hall G01",
    mode: "IN_PERSON",
    type: "TECH_TALK",
    categories: ["SWE", "ML / AI"],
    registrationUrl: "https://www.perplexity.ai/careers",
    sourceName: "Cornell Bowers CIS",
    sourceUrl: "https://www.cs.cornell.edu/events",
    discoveredAt: "2026-09-21T14:20:00Z",
    isMock: true,
  },
  {
    id: "palantir-info",
    slug: "palantir-forward-deployed-info-session",
    title: "Forward Deployed Engineering Info Session",
    description:
      "Learn how Forward Deployed Engineers work with customers to deploy production software against high-impact, ambiguous problems. Includes internship recruiting details.",
    company: "Palantir",
    companyInitials: "PL",
    companyColor: "#171717",
    startAt: "2026-09-24T17:30:00-04:00",
    endAt: "2026-09-24T18:30:00-04:00",
    location: "Statler Hall 196",
    mode: "IN_PERSON",
    type: "INFO_SESSION",
    categories: ["SWE", "Product"],
    registrationUrl: "https://www.palantir.com/careers/students/",
    sourceName: "Cornell Handshake",
    sourceUrl: "https://career.cornell.edu/",
    discoveredAt: "2026-09-20T11:00:00Z",
    isMock: true,
  },
  {
    id: "nvidia-virtual",
    slug: "nvidia-ai-infrastructure-coffee-chat",
    title: "AI Infrastructure Coffee Chats",
    description:
      "Small-group conversations with NVIDIA engineers working across accelerated computing, compilers, and distributed ML systems.",
    company: "NVIDIA",
    companyInitials: "NV",
    companyColor: "#526b12",
    startAt: "2026-09-25T12:00:00-04:00",
    endAt: "2026-09-25T14:00:00-04:00",
    location: "Zoom",
    mode: "VIRTUAL",
    type: "COFFEE_CHAT",
    categories: ["ML / AI", "Hardware", "SWE"],
    registrationUrl:
      "https://www.nvidia.com/en-us/about-nvidia/careers/university-recruiting/",
    sourceName: "NVIDIA University Recruiting",
    sourceUrl:
      "https://www.nvidia.com/en-us/about-nvidia/careers/university-recruiting/",
    discoveredAt: "2026-09-19T09:15:00Z",
    isMock: true,
  },
  {
    id: "jpmorgan-deadline",
    slug: "jpmorgan-2027-software-engineer-deadline",
    title: "2027 Software Engineer Program — Priority Deadline",
    description:
      "Priority application deadline for the 2027 Software Engineer Program. Roles span backend, infrastructure, data platforms, and developer tooling.",
    company: "JPMorganChase",
    companyInitials: "JPM",
    companyColor: "#173d70",
    startAt: "2026-09-27T23:59:00-04:00",
    location: "Online application",
    mode: "VIRTUAL",
    type: "DEADLINE",
    categories: ["SWE", "Finance"],
    registrationUrl:
      "https://careers.jpmorgan.com/us/en/students/programs/software-engineer-summer",
    sourceName: "JPMorganChase Careers",
    sourceUrl:
      "https://careers.jpmorgan.com/us/en/students/programs/software-engineer-summer",
    discoveredAt: "2026-09-18T16:40:00Z",
    deadline: "2026-09-27T23:59:00-04:00",
    isMock: true,
  },
  {
    id: "cornell-fair",
    slug: "cornell-engineering-career-fair",
    title: "Engineering & Technical Career Fair",
    description:
      "Meet employers recruiting Cornell students for software, hardware, data, product, and engineering roles. Student registration required.",
    company: "Cornell Career Services",
    companyInitials: "CU",
    companyColor: "#b31b1b",
    startAt: "2026-09-30T11:00:00-04:00",
    endAt: "2026-09-30T16:00:00-04:00",
    location: "Barton Hall",
    mode: "IN_PERSON",
    type: "CAREER_FAIR",
    categories: ["SWE", "ML / AI", "Hardware", "Product", "Consulting"],
    registrationUrl: "https://career.cornell.edu/",
    sourceName: "Cornell Career Services",
    sourceUrl: "https://career.cornell.edu/events/",
    discoveredAt: "2026-09-17T13:00:00Z",
    isMock: true,
  },
  {
    id: "stripe-workshop",
    slug: "stripe-api-design-workshop",
    title: "Designing APIs Developers Love",
    description:
      "A practical workshop on API ergonomics, versioning, idempotency, and the tradeoffs behind reliable payments infrastructure.",
    company: "Stripe",
    companyInitials: "S",
    companyColor: "#5b47e0",
    startAt: "2026-10-02T19:00:00-04:00",
    endAt: "2026-10-02T20:15:00-04:00",
    location: "Duffield Hall 340",
    mode: "HYBRID",
    type: "WORKSHOP",
    categories: ["SWE", "Product"],
    registrationUrl: "https://stripe.com/jobs/university",
    sourceName: "Cornell Engineering",
    sourceUrl: "https://www.engineering.cornell.edu/events/",
    discoveredAt: "2026-09-21T18:05:00Z",
    isMock: true,
  },
];
export const findEvent = (slug: string) =>
  mockEvents.find((event) => event.slug === slug);
